sonar.projectKey=Venuluck_secure_cicd_pipeline
sonar.organization=venuluck
sonar.projectName=Secure DevSecOps CI/CD Pipeline

sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8